version: '3.8'

services:
  qr-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tecsoqr
    restart: unless-stopped
    ports:
      # Change this port if needed to avoid conflicts with 3x-ui
      - "3001:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge